### ISSUE TITLE
clientupdate raises exception if username is already set to the one specified.

### ISSUE THREAD

**Issue by spacecheese** [Murgeye/teamspeak3-python-api#5]
TS3Connection.clientupdate throws the following exception if the bot username is already set to the one specified:
`ts3.TS3Connection.TS3QueryException: Query failed with id=513 msg=nickname is already in use`

**Comment by Murgeye** [comment]
Hi, thank you for bringing up the issue and proposing a fix. However, I think that the API is correct in raising an Exception if you try to change your username to the one you already have. Otherwise, anyone calling these functions would have no way to know that the rename failed. Same goes for #3.

So I would opt to fix Murgeye/teamspeak3-python-bot#6 and Murgeye/teamspeak3-python-bot#7 in the actual bot implementation rather than here. But I'm open to discussion here. I will probably fix this tonight or tomorrow.
