### ISSUE TITLE
Update Events

### ISSUE THREAD

**Issue by nisutec** [Murgeye/teamspeak3-python-api#8]
Hallo,
I have used the Example from the README.
I can test for a Message Event by using `if type(event) is Events.TextMessageEvent:`. But why i can't check with `elif type(event) is Events.ClientEnteredEvent:` if a client is joining. How are the Event Names ?

My Code: https://pastebin.com/xt1BgESs

**Comment by Murgeye** [comment]
Hi,

the problem with your code is that on_event is a local method inside your main function. When the event handler is called, your on_event function is already out of scope.

This is problematic because internally I use blinker to send signals to the event listeners. Blinker uses weak references by default, causing it to "drop" the registered listener when it goes out of scope.

I have just pushed an update to the API that allows you to override this. I left the default weak refs in place (use a global function for on_event or add it to a global object to use it with weak refs) because I am not sure what changing this could break. I will investigate further.

For now, simply replace your calls to the register functions with the following (after updating the API of course):
```
ts3conn.register_for_server_events(on_event, weak_ref=False)
ts3conn.register_for_private_messages(on_event, weak_ref=False)
```
This should fix you problems. If it doesn't please ask again.

Note: Adding different event handlers for different events seems to be broken right now. I will fix this soon (hopefully tonight) and push another update. So
```
ts3conn.register_for_server_events(on_event1, weak_ref=False)
ts3conn.register_for_private_messages(on_event2, weak_ref=False)
```
will call both on_event1 and on_event2 for both events.

**Comment by Murgeye** [comment]
Fix for my last note should be up and running! (Note that you will still get duplicate events for "notifycliententerview" and "notifyclientleftview" if you subscribe to both server and channel events, as there is simply no way to differentiate the scope this event was sent in).

**Comment by nisutec** [comment]
Is it already possible to trigger a event when someone was banned or kicked. I can't find a event for this.

**Comment by Murgeye** [comment]
Those are ClientLeftEvents (either for the channel you are subscribed to or the server). The reason id on that is defined as follows (from the TeamSpeak query API, probably is the same for all reason IDs):

0 - Channel changed (self) or server entered

1 - User or Channel moved

3 - Timeout

4 - Channel kick

5 - Server kick

6 - Ban

8 - Left Server on own accord

10 - Server or Channel edited

11 - Server shutdown 

I *think* that the event is missing the invoker id, name and UID as wells as the ban time, simply because we have never had need for the kick an ban events (and I haven't seen them in our tests). I will probably add those values to the event tomorrow if I find the time.

**Comment by nisutec** [comment]
> I will probably add those values to the event tomorrow if I find the time.

that would be really nice.

**Comment by Murgeye** [comment]
Hey,
I have updated the API and added ClientKickedEvent and ClientBannedEvent. Both are subclasses of ClientLeftEvent and ClientBannedEvent is a subclass of ClientKickedEvent.

Try this:
```
def on_event(sender, **kw):
    """
    Event handling method
    """
    # Get the parsed event from the dictionary
    event = kw["event"]
    print(type(event))
    """
    # This generates output for every event. Remove the comment if you want more output
    for attr, value in event.__dict__.items():
        print("\t"+attr+":", value)
    """
    if isinstance(event, Events.ClientBannedEvent):
        print("Client was banned!")
        print("\tClient ID:", event.client_id)
        print("\tReason Message:", event.reason_msg)
        print("\tInvokerID:", event.invoker_id)
        print("\tInvokerName:", event.invoker_name)
        print("\tBantime:", event.ban_time)
    if isinstance(event, Events.ClientKickedEvent):
        print("Client was kicked!")
        print("\tClient ID:", event.client_id)
        print("\tReason Message:", event.reason_msg)
        print("\tInvokerID:", event.invoker_id)
        print("\tInvokerName:", event.invoker_name)

    if isinstance(event, Events.ClientLeftEvent):
        print("Client left!")
        print("\tClient ID:", event.client_id)
        print("\tReason Message:", event.reason_msg)
    if type(event) is Events.TextMessageEvent:
        # Prevent the client from sending messages to itself
        if event.invoker_id != int(ts3conn.whoami()["client_id"]):
            ts3conn.sendtextmessage(targetmode=1, target=event.invoker_id, msg="I received your message!")
```
Due to the instanceof calls, a Ban should print all three events, a kick two and a client simply leaving the server only the first one. Please try that and tell me if it works!

**Comment by nisutec** [comment]
Nice it works.
But on the `ClientBannedEvent` and `ClientKickedEvent` is the `event.client_uid` Variable not set. The Variable `event.invoker_uid` works.

**Comment by Murgeye** [comment]
Sadly the Teamspeak server does not simply send the client_uid for this event. 

I'm not sure how to get it because clientinfo will not work for client ids of clients that are already gone. I am a bit short of time today, but I will look into that tomorrow.

**Comment by nisutec** [comment]
ok thx

**Comment by Murgeye** [comment]
I think there is not much I can do on the API side. The only information about the client I get with the notifyclientleftview Event (that I parse into the ClientLeftEvent) is the clid (client id). But as the client is gone from the server after banning/kicking them the id is invalidated by the server and there seems to be no command to get information about the client uid.

I guess the easiest solution for you would be to maintain a mapping of UIDs to IDs and add to that on a ClientEnteredEvent and remove the ID on a ClientLeftEvent. I am of the opinion that that should not be implemented in the API but rather in the bot.

**Comment by nisutec** [comment]
> I guess the easiest solution for you would be to maintain a mapping of UIDs to IDs and add to that on a ClientEnteredEvent and remove the ID on a ClientLeftEvent.

That is a really nice idea i will try this.

**Comment by nisutec** [comment]
it works perfect
